name: Pull request checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  code-checks:
    name: code-checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Run eslint
        run: yarn eslint:lint

      - name: Check prettier formatting
        run: yarn prettier:check

  code-build:
    name: code-build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Build
        run: yarn build
